//modules
import type { Directory, SourceFile } from 'ts-morph';
//stackpress-schema
import type Model from 'stackpress-schema/Model';
import { loadProjectFile } from 'stackpress-schema/transform/helpers';

type TestModule = {
  moduleSpecifier: string,
  name: string
};

function getTestModules(model: Model) {
  return [
    {
      moduleSpecifier: model.name.toPathName('./tests/%sStore.test.js'),
      name: model.name.toClassName('%sStoreTests')
    },
    {
      moduleSpecifier: model.name.toPathName('./tests/%sActions.test.js'),
      name: model.name.toClassName('%sActionTests')
    },
    {
      moduleSpecifier: './tests/events.test.js',
      name: model.name.toClassName('%sEventsTests')
    }
  ];
};

function addDefaultImport(source: SourceFile, module: TestModule) {
  const existing = source.getImportDeclarations().find(declaration => (
    declaration.getModuleSpecifierValue() === module.moduleSpecifier
  ));

  if (existing) {
    existing.setDefaultImport(module.name);
    return;
  }

  source.addImportDeclaration({
    moduleSpecifier: module.moduleSpecifier,
    defaultImport: module.name
  });
};

export function generateModelTests(directory: Directory, model: Model) {
  const modules = getTestModules(model);
  const filepath = model.name.toPathName('%s/tests.ts');
  //load Profile/tests.ts generated by stackpress-schema
  const source = loadProjectFile(directory, filepath);

  //------------------------------------------------------------------//
  // Import Client

  for (const module of modules) {
    addDefaultImport(source, module);
  }

  //------------------------------------------------------------------//
  // Exports

  const runnerName = model.name.toClassName('runAll%sTests');
  const runner = source.getFunction(runnerName);
  const sqlStatements = modules.map(module => (
    `runTestRunner(${module.name} as unknown as TestRunner, engine);`
  ));

  if (runner) {
    const schemaStatements = runner.getStatements().map(
      statement => statement.getText()
    ).filter(statement => !statement.includes('StoreTests')
      && !statement.includes('ActionTests')
      && !statement.includes('EventsTests')
    );
    runner.setBodyText([
      ...schemaStatements,
      ...sqlStatements
    ].join('\n'));
  }
};

